apiVersion: v1
kind: Service
metadata:
  name: autoscaling-nginx-service
  namespace: autoscaling-lab
spec:
  selector:
    app: autoscaling-nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

