apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-nginx
  namespace: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-nginx
  template:
    metadata:
      labels:
        app: secure-nginx
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10101
        runAsGroup: 10101
        capabilites:
          drop:
          - ALL
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    ports:
    - containerPort: 80

