apiVersion: v1
kind: Service
metadata:
  name: gitops-nginx-service
  namespace: default
spec:
  selector:
    app: gitops-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
