apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-new
  namespace: deployment-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
      version: new
  template:
    metadata:
      labels:
        app: canary-app
        version: new
    spec:
      containers:
      - name: nginx
        image: nginx:1.26-alpine
        ports:
        - containerPort: 80
